### PR TITLE
Courageously reformat source code

### LINKED ISSUE #42: coding convention

### PR DESCRIPTION
**Pull request by frobware**
Reformat the source code using clang-format --style=webkit

The webkit style is defined here: https://webkit.org/code-style-guidelines/

Fixes #42.

Signed-off-by: Andrew McDermott <aim@frobware.com>

### CODE REVIEW

**Comment by frobware** [comment]
Note: maybe a better alternative is to use clang-format(1) and that could be part of a pre-commit git push hook. Thoughts? At least clang-format could be automatically done at commit time.

**Comment by jdmnd** [comment]
I agree that the project lacks some consistency with indentation and I prefer the style that you're suggesting. It's a shame there isn't a neater way of nesting namespaces without greatly increasing the nesting (e.g. in `client.cpp`).
clang-format is a good idea, we'll look at that more when we finish setting up CI on this repo.
Is the format here one that is enforced by clang-format? If so, I'm happy to merge.

**Comment by frobware** [comment]
The style in this commit is not based on clang-format. With clang-format you can have:

- LLVM
- Google
- Chromium
- Mozilla
- WebKit

I suggest not to merge this because of the churn. I just got fed up with random indents. I still think this should be done but, as you suggest, perhaps less nesting of namespaces would actually be better still.

Interestingly, I noted the following:

- https://github.com/andrewseidl/githook-clang-format

**Comment by jdmnd** [comment]
To be honest I'd rather have travis CI setup to warn about incorrect style as opposed to having it apply any formatting changes itself. That seems quite 'magic' and might muddy the commit history. 
I haven't used CLion, but I'm guessing there's a way it can be configured to apply clang-format on write. 
Any preference between the style guides listed?

**Comment by frobware** [comment]
I would choose one of the big four, but if you want less nesting, then LLVM does that by default.

I think you if don't enforce it in a pre-commit hook you'll get a lot of commits which then need fixing up. Go-based projects successfully handle running ```go fmt``` as a pre-commit hook. I don't see much difference here.

I didn't want to start a style war. :-)

I just want the tools and tooling to do it automatically so it becomes ultimately consistent and something you don't have to track. Having used Go for quite a while now you forget about all these shenanigans because it just happens either OOTB (editor save hook), or is enforced by a pre-commit hook.

I'll force push a change that shows the tree formatted with clang-format -- all with default settings.

**Comment by jdmnd** [comment]
👍 
I mis-understood initially, a pre-commit hook sounds like great idea, had thought assumed the link was pre-merge.

**Comment by frobware** [comment]
The alternative is to have the pre-commit hook but fail if running clang-format on what is to be committed detects a difference. In this way it doesn't alter what has been committed, just that the pre-commit hook fails and then you have a choice: 

- you can either edit the .git/hook and comment the check out
- manually run clang-format (and squash your commit) then push again.

The advantage of just checking and exiting if there is a difference is you can override it, if necessary.

**Comment by jdmnd** [comment]
Agreed. And this format looks good to me.

**Comment by frobware** [comment]
I actually think formatting with `clang-format --style=webkit` looks much better. The presentation of nested namespaces is indented. The first is not, which makes sense, the second, third are and so on.

I think relying on CLion is a mistake - you want something that can run from the command line.

**Comment by jdmnd** [comment]
The namespace thing makes sense, 4 spaces is easier to read as well in my opinion

**Pull request merged**
